apiVersion: v1
kind: Service
metadata:
  labels:
      app: nginx
  name: myapp
  namespace: default
spec:
  selector:
    app: myapp
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
